mod number;
mod binary_operation;
mod identifier;
mod assignment;
mod scope;
mod function;
mod file;
mod r#return;
mod declaration;
mod call;
mod parameter;
mod ternary;
mod if_else;

pub use number::*;
pub use binary_operation::*;
pub use identifier::*;
pub use assignment::*;
pub use scope::*;
pub use function::*;
pub use file::*;
pub use r#return::*;
pub use declaration::*;
pub use call::*;
pub use parameter::*;
pub use ternary::*;
pub use if_else::*;